# Screen dimensions
WIDTH, HEIGHT = 800, 600
# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
# Darkening effect higher value = less darkening
DARKENING_FACTOR = 60
# Rendering distance
RENDER_DISTANCE_FAR = DARKENING_FACTOR
RENDER_DISTANCE_BEHIND = -3.1
RENDER_DISTANCE_RIGHT = 50
RENDER_DISTANCE_LEFT = -RENDER_DISTANCE_RIGHT
